Repository willGyu/team3, pull requests merged in 2023-10, with the labels that each got.

#2 feat:기능1 구현완료
  Team3/src/main/java/com/team/team3/2기능1 구현하기
  Team3/target/classes/com/team/team3/2기능1 구현하기
Labels: question

#4 팀원a-기능2완료
  Team3/Team3/.gitignore
  Team3/Team3/Spring/workspace_sts2/Team3/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  Team3/Team3/Spring/workspace_sts2/Team3/target/m2e-wtp/web-resources/META-INF/maven/com.team/team3/pom.properties
  Team3/Team3/Spring/workspace_sts2/Team3/target/m2e-wtp/web-resources/META-INF/maven/com.team/team3/pom.xml
  Team3/Team3/pom.xml
  Team3/Team3/src/main/java/com/team/team3/1프로젝트세팅.txt
  Team3/Team3/src/main/java/com/team/team3/3팀원기능2.txt
  Team3/Team3/src/main/java/com/team/team3/HomeController.java
  Team3/Team3/src/main/resources/log4j.xml
  Team3/Team3/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  Team3/Team3/src/main/webapp/WEB-INF/spring/root-context.xml
  Team3/Team3/src/main/webapp/WEB-INF/views/home.jsp
  Team3/Team3/src/main/webapp/WEB-INF/web.xml
  Team3/Team3/src/test/resources/log4j.xml
  Team3/Team3/target/classes/com/team/team3/1프로젝트세팅.txt
  Team3/Team3/target/classes/log4j.xml
  Team3/Team3/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  Team3/Team3/target/m2e-wtp/web-resources/META-INF/maven/com.team/team3/pom.properties
  Team3/Team3/target/m2e-wtp/web-resources/META-INF/maven/com.team/team3/pom.xml
  Team3/Team3/target/test-classes/log4j.xml
Labels: good first issue

#5 feat-팀장구현기능1
  Team3/src/main/java/com/team/team3/2기능1 구현하기
  Team3/target/classes/com/team/team3/2기능1 구현하기
Labels: documentation

#6 Mod a
  Team3/src/main/java/com/team/team3/3팀원기능2.txt
Labels: bug
